name: .NET Core

on:
  push:
    branches: [ master ]
    
jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
         
    - name: DotNet Restore
      run: dotnet restore
    
    - name: DotNet Publish
      run: dotnet publish ./WebHook/WebHook.csproj -c Release -r linux-x64 -p:PublishReadyToRun=true --self-contained false
      
    - name: Stop ScheduleBot Service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: systemctl stop ScheduleBot
        host: ${{ secrets.REMOTE_HOST }}
        port: 10022
        username: ${{ secrets.REMOTE_USER }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
      
    - name: Copy to Server via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: 10022
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: /home/runner/work/TulsuScheduleBot/TulsuScheduleBot/WebHook/bin/Release/net8.0/linux-x64/publish/*
        target: ${{ secrets.REMOTE_TARGET }}
        rm: true
      
    - name: Start ScheduleBot Service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: systemctl start ScheduleBot
        host: ${{ secrets.REMOTE_HOST }}
        port: 10022
        username: ${{ secrets.REMOTE_USER }}
        passphrase: ${{ secrets.PASSPHRASE }}
        privateKey: ${{ secrets.REMOTE_SSH_KEY }}
